version: "3.9"
services:
  backend:
    image: ghcr.io/ch-bj/lgs-person-data-processor-service:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - internal
      - default
    volumes:
      - log_data:/logs
      - hsqldb_data:/hsqldb/data
      - sedex:/var/sedex
    links:
      - rabbitmq
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_JDBC_URL: ${DB_JDBC_URL}
      DB_HIBERNATE_DIALECT: ${DB_HIBERNATE_DIALECT}
      DB_DRIVER_CLASS_NAME: ${DB_DRIVER_CLASS_NAME}
      SEDEX_BASE_PATH: "/var/sedex"
      SEDEX_SENDER_ID: ${SEDEX_SENDER_ID}
      SEDEX_RECIPIENT_ID: ${SEDEX_RECIPIENT_ID}
      SEDEX_MESSAGE_TYPE_FULL_EXPORT: ${SEDEX_MESSAGE_TYPE_FULL_EXPORT}
      SEDEX_MESSAGE_TYPE_INCREMENTAL: ${SEDEX_MESSAGE_TYPE_INCREMENTAL}
      REST_API_KEY: ${REST_API_KEY}
      PARTIAL_SYNC_PAGE_SIZE: ${PARTIAL_SYNC_PAGE_SIZE:-10000}
      PARTIAL_SYNC_SCHEDULING_TYPE: ${PARTIAL_SYNC_SCHEDULING_TYPE:-FIXED_DELAY}
      PARTIAL_SYNC_CRON_SCHEDULE: ${PARTIAL_SYNC_CRON_SCHEDULE:-0 0 * * * ?}
      PARTIAL_SYNC_FIXED_DELAY: ${PARTIAL_SYNC_FIXED_DELAY:-300000}
      FULL_SYNC_PAGE_SIZE: ${FULL_SYNC_PAGE_SIZE:-10000}
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-fH", "Authorization: token ${REST_API_KEY}", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  postgres:
    image: 'postgres:15-alpine'
    restart: always
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    profiles:
      - postgres
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    networks:
      - default
      - internal
    ports:
      - "127.0.0.1:8082:15672"
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/docker-presets.conf
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbit_data:/var/lib/rabbitmq/mnesia
      - rabbit_logs:/var/log/rabbitmq/log
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  prometheus:
    image: prom/prometheus
    restart: always
    networks:
      - internal
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - rabbitmq
      - backend
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "127.0.0.1:8083:3000"
    networks:
      - internal
      - default
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./docker/grafana/dashboards:/dashboards
    environment:
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
    links:
      - prometheus
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  log_data: {}
  hsqldb_data: {}
  postgres_data: {}
  rabbit_data: {}
  rabbit_logs: {}
  grafana_data: {}
  sedex: {}
networks:
  internal:
