{
 "title": "LWGS Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Partial Incoming",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"lwgs.persondata.partial.incoming\"}"
    }
   ]
  },
  {
   "title": "Partial Outgoing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"lwgs.persondata.partial.outgoing\"}"
    }
   ]
  },
  {
   "title": "Sedex Outbox",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"lwgs.sedex.outbox\"}"
    }
   ]
  },
  {
   "title": "Sedex Receipts",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"lwgs.sedex.recepits\"}"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages" }
   ]
  },
  {
   "title": "Partial Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"lwgs.persondata.partial.failed\"}"
    }
   ]
  },
  {
   "title": "Full Incoming",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"lwgs.persondata.full.incoming\"}"
    }
   ]
  },
  {
   "title": "Full Outgoing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"lwgs.persondata.full.outgoing\"}"
    }
   ]
  },
  {
   "title": "Full Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"lwgs.persondata.full.failed\"}"
    }
   ]
  }
 ]
}